In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
y_data = torch.tensor([[1,2],[3,4]])
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [3]:
x_ones = torch.ones_like(x_data)
print(f"x_data : \n {x_data}\n")
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

x_data : 
 tensor([[1, 2],
        [3, 4]])

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4239, 0.0365],
        [0.2389, 0.5400]]) 



In [4]:
shape = (2,3,)
print(f"Random Tensor :\n {torch.rand(shape)}")
print(f"One Tensor : \n {torch.ones(shape)}")
print(f"Zero Tensor : \n {torch.zeros(shape)}")


Random Tensor :
 tensor([[0.4124, 0.5302, 0.4071],
        [0.4346, 0.6275, 0.3769]])
One Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zero Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


텐서의 속성은 텐서의 모양(shape), 자료형(dtype), 저장장치(device)를 나타냅니다.

In [5]:
tensor = torch.rand(3,4)

print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of Tensor : {tensor.dtype}")
print(f"Device tensor is stored on : {tensor.device}")


Shape of tensor : torch.Size([3, 4])
Datatype of Tensor : torch.float32
Device tensor is stored on : cpu


torch.backends.mps.is_available(): mps device 사용 가능여부확인(가능=true/불가능=false)


In [6]:
# Check that MPS is available
if not torch.backends.mps.is_available():
    if not torch.backends.mps.is_built():
        print("MPS not available because the current PyTorch install was not "
              "built with MPS enabled.")
    else:
        print("MPS not available because the current MacOS version is not 12.3+ "
              "and/or you do not have an MPS-enabled device on this machine.")
else:
    print("MPS is available")

MPS is available


torch.device("device"): "device"변수
tensor = tensor.to("torch.device("device")): tensor를 "device"에 할당

In [7]:
if torch.backends.mps.is_available():
    tensor_device=torch.device("mps")
else:
    tensor_device=torch.device("cpu")
tensor = tensor.to(tensor_device)
print(f"Device tensor is stored on : {tensor.device}")

Device tensor is stored on : mps:0


In [8]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[:,-1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


``` python
torch.cat([tensor, tensor, ...], dim=N)
```
- N=0: row
- N=1: column

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(f"torch.cat: {t1}")


torch.cat: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


매트릭스 곱
``` python
tensor_out=tensor1@tensor2
tensor_out=tensor1.matmul(tensor2)
torch.matmul(tensor1,tensor2, out=tensor_out)
```

In [10]:
y1 = tensor@tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

y1, y2, y3

(tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]))

element-wise product
``` python
tensor_out=tensor1*tensor2
tensor_out=tensor1.mul(tensor2)
torch.mul(tensor1, tensor2, out=tensor_out)
```

In [11]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

z1, z2, z3

(tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]),
 tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]),
 tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]))

all elements sum
``` python
tensor_out = tensor.sum()
```
convert tensor to python num
``` python
python_num = tensor.item()
```

In [12]:
agg = tensor.sum()
print(agg, type(agg))
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


In place operation
``` python
tensor.operator_(num)
```

In [13]:
tensor = torch.ones((5,5))
print(f"tensor is \n{tensor}")
tensor.add_(5)
print(f"tensor is \n{tensor}")
tensor.mul_(5)
print(f"tensor is \n{tensor}")



tensor is 
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor is 
tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])
tensor is 
tensor([[30., 30., 30., 30., 30.],
        [30., 30., 30., 30., 30.],
        [30., 30., 30., 30., 30.],
        [30., 30., 30., 30., 30.],
        [30., 30., 30., 30., 30.]])


# Nuympy 변환
CPU 상의 텐서와 Numpy배열은 메모리 공간을 공유한다.

In [14]:
tensor = torch.ones(5)
print(f"tensor: {tensor}")
n = tensor.numpy()
print(f"n: {n}")

tensor: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [15]:
tensor.add_(1)
print(f"tensor: {tensor}")
print(f"n: {n}")

tensor: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [16]:
np.add(n, 1, out=n)
print(f"tensor: {tensor}")
print(f"n: {n}")

tensor: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
